### ISSUE TITLE
Compiling on OS X (10.11) 

### ISSUE THREAD

**Issue by jbat100** [adamstark/Sound-Analyser#4]
I've compiled the project on OS X 10.11 but it's taken a bit of tweaking. I've had to update to the latest versions of the JUCE libraries to get some fixes, and this broke a few things. Namely a few abstract method signature changes which caused some compilation errors, and a DatagramSocket API change.

I've committed the changes to my fork 

https://github.com/jbat100/Sound-Analyser
commit d25c07271aead004eda5680e25d62130ac5bb342 

In case you want to pull it

**Comment by adamstark** [comment]
Hi there,

Thanks for this! I will definitely look into this as soon as I move to JUCE 4. I'm not at the moment as it causes some large problems for another project, but i will be soon. I expect for the SoundAnalyser I will update to the new JUCE OSC classes too, losing my lo-fi OSC implementation here.

I'll keep you posted!

Thanks,

Adam

**Comment by adamstark** [comment]
I have now updated the project to JUCE 4, as well as some other things (e.g. changing the OSC implementation). :)
