### ISSUE TITLE
Frequency modulation (FM)

### ISSUE THREAD

**Issue by MichaelZP** [adamstark/Sound-Analyser#5]
How to modulate one waveform/track with another to achieve FM(Freq. Modulation)?
![fm_](https://cloud.githubusercontent.com/assets/17249917/16712012/ed8aaab8-4678-11e6-9b67-4c44ac081e7f.jpg)

**Comment by adamstark** [comment]
The Sound Analyser plug-in doesn't do any synthesis or FM. There are lots of tutorials on this, e.g.:

https://www.propellerheads.se/blog/thor-demystified-9-an-introduction-to-fm-synthesis-part-1
http://www.acoustics.salford.ac.uk/acoustics_info/sound_synthesis/
https://ccrma.stanford.edu/software/snd/snd/fm.html

Good luck! :)

**Comment by MichaelZP** [comment]
Thank You for quick response and good info. :+1:
