### ISSUE TITLE
request - 64bit

### ISSUE THREAD

**Issue by flowen** [adamstark/Sound-Analyser#6]
Hey Adam, awesome plugin! Was wondering (but really I have no clue how or if this is a lot of work) you could compile to a 64bit version. Assuming it's 32bit, Live is unable to host because of the difference. Appreciate the work you did!

**Comment by adamstark** [comment]
Hey,

This is something I've had quite a lot of requests for recently so I will get on and do it soon! The only reason I haven't so far is that there are some library compatability issues that I need to solve first. I'll find some time and will get it done as soon as I can. :)

Cheers!

Adam

**Comment by flowen** [comment]
Looking forward to it :)
